settings:
  username: "trinib"
  commit_msg: " ğŸ”¥â„ğ”¼ğ”¸ğ”»ğ•„ğ”¼ ğ•Œâ„™ğ”»ğ”¸ğ•‹ğ”¼ğ”» â­ Star Kodi  "
  max_lines: 0
  readme_file: "README.md"
  disabled_events: [event1, event2, event3]
  url_text: "{REPO}{ID}"

  date:
    timezone: "Asia/Kolkata"
    text: "<i>Last refresh</i> : <b>{DATE}</b>"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"

  commit_name: "HengeNaavu-Bot"
  commit_email: "131793517+HengeNaavu-Bot@users.noreply.github.com"
